import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import {
  ClerkProvider,
  Show,
  UserButton,
} from "@clerk/nextjs";
import { dark } from "@clerk/ui/themes";
import { AuthButtons } from "@/components/auth/AuthButtons";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${poppins.className} dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider
          appearance={{
            theme: dark,
            elements: {
              modalBackdrop: "bg-black/80 backdrop-blur-sm",
              modalContent: "bg-background text-foreground border border-border",
              card: "bg-background text-foreground border border-border shadow-none",
              headerTitle: "text-foreground",
              headerSubtitle: "text-muted-foreground",
            },
          }}
        >
          <header className="w-full flex items-center justify-end gap-3 p-4">
            <Show when="signed-out">
              <AuthButtons />
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
